### Данные для API
base_url="https://api.travelpayouts.com/aviasales/v3/"
base_url_2 = "http://api.travelpayouts.com/v2/"
base_url_3 = "https://api.travelpayouts.com/v1/"
token="55a3c1475e666fa6c02af4ea1632a891"
airline_code="J2"
currency="AZN"
depart_date="2025-04-08"
return_date="2025-04-16"
destination="IST"
limit="10"
origin="GYD"
page="1"


### Данные для UI
base_url_ui="https://www.aviasales.ru/"
base_url_pa="https://www.aviasales.az/my/documents?market=az"
departure_city="Баку"
destination_city="Стамбул"
departure_date="2025-04-08"
first_name=""
last_name=""
date_bd=""
document_number=""
